### ISSUE TITLE
typo in pod.yaml

### ISSUE THREAD

**Issue by exxa-tech** [altalang/ofs#2]
In your pod.yaml file:

  volumes:
  - name: test
    flexVolume:
      driver: "altlang/ofs"

Everywhere else - it is altalang/ofs.

ofs-secret seems to be referencing it.

If I change pod.yaml to the correct spelling (altalang/ofs):

MountVolume.SetUp failed for volume "test" : Couldn't get secret default/ofs-secret err: Cannot get secret of type altalang/ofs

If I have original spelling:

 Unable to attach or mount volumes: unmounted volumes=[test], unattached volumes=[default-token-w2xv9 test]: failed to get Plugin from volumeSpec

Running EKS 1.19. I have done a bunch of testing and everything else seems to work - running ofs init on worker and master nodes are successful.

Would love your thoughts.
Thanks,
Alastair

**Comment by btorellALTA** [comment]
Thanks, fixed.

**Comment by btorellALTA** [comment]
> MountVolume.SetUp failed for volume "test" : Couldn't get secret default/ofs-secret err: Cannot get secret of type altalang/ofs

That probably means you either didn't set up the secret correctly, or are referring to it with the wrong name in your pod config.
